import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-black text-white">
  <header className="w-full border-b border-zinc-800">
    <div className="max-w-6xl mx-auto px-4 py-3 flex justify-between items-center">
      <a href="/" className="font-bold text-lg">
        ThiranX
      </a>

      <a
        href="/login"
        className="text-sm border border-zinc-700 px-4 py-2 rounded-lg hover:bg-zinc-900"
      >
        Login
      </a>
    </div>
  </header>

  {children}
</body>

    </html>
  );
}
